apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: es-homeassistant
  namespace: external-services
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        enabled: true
        externalIP: ${HOMEASSISTANT_IP}
        useSlice: false
        ports:
          main:
            enabled: true
            port: ${HOMEASSISTANT_PORT}
            protocol: http
        type: ExternalIP
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: home.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
